### ISSUE TITLE
Reference Manual page 23, 9.2 assemble example escape \$6000

### ISSUE THREAD

**Issue by eriktier** [paulscottrobson/superbasic#30]
The example of the assemble command contains an escape character that shouldn't not be there in the pdf:

100 assemble \$6000, ....

Should be just $6000.

**Comment by eriktier** [comment]
it also mentions that the assembled bytes will be output to the screen, which doesn't happen (not sure if it would make sense if they did).

**Comment by paulscottrobson** [comment]
Wrong way round ....
