### ISSUE TITLE
Unable to 'ctrl-c' the listing of a procedure

### ISSUE THREAD

**Issue by eriktier** [paulscottrobson/superbasic#35]
When listing a long procedure (like ml_routines() in Ernesto's sprite editor), it does not seem possible to break the listing with ctrl-c, like you can with 'regular' listing. It would be very handy if this is possible.

**Comment by paulscottrobson** [comment]
Good spot ! Fixed in release.

**Comment by eriktier** [comment]
Confirmed! :)
