### ISSUE TITLE
SolarFox, Demo2 and Invaders fail with Out of Range errors

### ISSUE THREAD

**Issue by eriktier** [paulscottrobson/superbasic#37]
After updating to the 01/03/2023 Beta 1 version of Basic/Kernel, I notice that these two demo games don't work anymore. Both fail in a routine that updates or draws all sprites with an Out of Range error. Perhaps this is caused by the changes in the sprite handling code.

**Comment by paulscottrobson** [comment]
Probably, as it seems to work on my machine ; I did update all the various demos that use sprites as they require new graphics.bin files ; old ones will probably do something odd ?
