### ISSUE TITLE
Inserting code while editing an existing line should not cut off the last characters that fall off the screen

### ISSUE THREAD

**Issue by eriktier** [paulscottrobson/superbasic#38]
When you edit an existing line of code and insert characters before the end, any character that is pushed off the screen is lost, which can lead to some really weird errors. These characters should be preserved. It would be the best if they would just flow onto the next line.

**Comment by paulscottrobson** [comment]
This is now blocked. There is a consequential problem, because the tokenising and detokenising can add spacing to push this up into a second line, which the screen editor cannot currently deal with.
