### ISSUE TITLE
SD Card access does not work

### ISSUE THREAD

**Issue by rmsk2** [paulscottrobson/superbasic#41]
When using the latest released version of superbasic (Beta 1) on my Foenix 256 Jr. I am unable to list the directory of an SD card or `save` a basic program to an SD card. Because saving was not possible I also could not try to `load` a basic program. When issuing a `dir` command no error message is printed and  no files are listed. A `save` command results in a `storage error`. The SD card LED on the board does not light up or blink.

I have tried several cards (16MB SD, 128MB SD, 512MD SD, 2GB SD, 4GB SDHC) which have been formatted on Linux and on Windows using FAT32. When formatting I have tried several different allocation unit sizes (512, 1024, 2048 and 4096 bytes) and I also have repartitioned the cards on Windows. I also had a look at https://github.com/ghackwrench/F256_Jr_Kernel_DOS for additional information but was not able to solve my problem. 

Am I just unlucky with my selection of SD cards or is this is a known bug of this version? 

As a side note: Listing a directory, `save` or `load` work for IEC bus devices (I have checked that with a real 1541 floppy drive and an `sd2iec` like device.

**Comment by paulscottrobson** [comment]
Hi. I suggest you go into DOS (/DOS) and see if you can to a directory from there. All I'm really doing is calling the directory API and printing out what I get back.

**Comment by rmsk2** [comment]
Hi, thanks for the info. In the DOS CLI I get the error message `no media present` when issuing a `dir` command. So it seems that not even the presence of a card is detected, which is probably the most fundamental error possible ;-). If SD card access works for others then it must be a problem on my side. Either with my SD cards or with my board.

**Comment by rmsk2** [comment]
I have found some additional things to try in the kernel release notes. Thanks again for the Info.

**Comment by rmsk2** [comment]
Accessing the SD card now works. For the benefit of people who might experience the same problem as I did here the solution to this problem according to https://github.com/ghackwrench/F256_Jr_Kernel_DOS/blob/main/ReleaseNotes.txt

Main points:

- The kernel is only probing the SD Card once, at startup;  for now, you will need to reboot when you swap cards. Removing and re-inserting the same card without a reboot  will not work!
-    The SPI layer is presently only supporting V2 SD Cards (these are modern HC and XC cards).  Older V1 cards won't work (this is primarily a software limitation)
-   The FAT layer won't handle off-the-shelf format parameters;  you will need to format the card from the Foenix to ensure compatibility.

Formatting is possible by issuing the `mkfs` command in the DOS CLI that can be launched from BASIC through the command `/DOS`.
